services:
  zeebe-mock:
    build:
      context: ..
      dockerfile: ./images/zeebemock/Dockerfile
    environment:
      ZEEBEMOCK_WIREMOCKURI: http://wiremock:8080

      CAMUNDA_CLIENT_MODE: self-managed
      CAMUNDA_CLIENT_ZEEBE_ENABLED: true
      CAMUNDA_CLIENT_ZEEBE_GRPC_ADDRESS: http://zeebe:26500
      CAMUNDA_CLIENT_ZEEBE_REST_ADDRESS: http://zeebe:8080
      CAMUNDA_CLIENT_ZEEBE_PREFER_REST_OVER_GRPC: false
    networks:
      - local_camunda-platform
      - local_default

networks:
  local_camunda-platform:
    external: true
  local_default:
    external: true