name: Create and publish a Docker image
on:
  push:
    branches: [ "main" ]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - name: zeebe-mock
            path: ./images/zeebemock/Dockerfile
          - name: zeebe-mock-wiremock
            path: ./images/wiremock/Dockerfile
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # https://docs.docker.com/build/ci/github-actions/multi-platform/#build-and-load-multi-platform-images
      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: hombro/${{ matrix.image.name }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          platforms: linux/amd64,linux/arm64
          load: true
          context: .
          file: ${{ matrix.image.path }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Generate artifact attestation
        # disable until public repo
        if: false
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: hombro/${{ matrix.image.name }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true